// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBMZyzqJWg8gfAsyl4_n94xlMjwRSIzaA',
    appId: '1:963945047580:web:8f8ed357f11f32b451a1d9',
    messagingSenderId: '963945047580',
    projectId: 'rndm-13d1c',
    authDomain: 'rndm-13d1c.firebaseapp.com',
    databaseURL: 'https://rndm-13d1c.firebaseio.com',
    storageBucket: 'rndm-13d1c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcB_GORjGeiVbKUA41D4ZKHpRSAvcHxgU',
    appId: '1:963945047580:android:455ef91e18edae0a51a1d9',
    messagingSenderId: '963945047580',
    projectId: 'rndm-13d1c',
    databaseURL: 'https://rndm-13d1c.firebaseio.com',
    storageBucket: 'rndm-13d1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwkkuW_KIr3lsPUNBEUwlviNTDJnHU3Es',
    appId: '1:963945047580:ios:0b150fa3aea3f2e351a1d9',
    messagingSenderId: '963945047580',
    projectId: 'rndm-13d1c',
    databaseURL: 'https://rndm-13d1c.firebaseio.com',
    storageBucket: 'rndm-13d1c.appspot.com',
    androidClientId: '963945047580-eqjcmoaeeqobmnr770mv6e1je9e27m7f.apps.googleusercontent.com',
    iosClientId: '963945047580-erhj167o4kcaer9coq1kiroo5jg9ojl8.apps.googleusercontent.com',
    iosBundleId: 'com.usjr.mobile.usjrFirebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwkkuW_KIr3lsPUNBEUwlviNTDJnHU3Es',
    appId: '1:963945047580:ios:0b150fa3aea3f2e351a1d9',
    messagingSenderId: '963945047580',
    projectId: 'rndm-13d1c',
    databaseURL: 'https://rndm-13d1c.firebaseio.com',
    storageBucket: 'rndm-13d1c.appspot.com',
    androidClientId: '963945047580-eqjcmoaeeqobmnr770mv6e1je9e27m7f.apps.googleusercontent.com',
    iosClientId: '963945047580-erhj167o4kcaer9coq1kiroo5jg9ojl8.apps.googleusercontent.com',
    iosBundleId: 'com.usjr.mobile.usjrFirebaseFlutter',
  );
}
